/*Gabriel Mayo w860898
 CSC 412 - Intro to AI
 Ins. Bryant Walley
 Slider Puzzle Solver
 10-31-2017, 11-7-2017, 11-14-2017*/
using System.Windows;

namespace SliderPuzzleSolver
{
    //This file was generated by the IDE.
    //I didn't use it at all but I'm scared to delete it.
    public partial class App : Application
    {
    }
}
